# permissions for end users to edit idlingresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: idlingresource-editor-role
rules:
- apiGroups:
  - kidle.kidle.dev
  resources:
  - idlingresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kidle.kidle.dev
  resources:
  - idlingresources/status
  verbs:
  - get
