
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kidle.beroot.org
  resources:
  - idlingresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kidle.beroot.org
  resources:
  - idlingresources/status
  verbs:
  - get
  - patch
  - update
